version: "3.8"

services:
  statsd_exporter:
    image: prom/statsd-exporter
    command: "--statsd.mapping-config=/tmp/statsd_mapping.yml"
    ports:
      - "9102:9102"
      - "8125:9125"
      - "8125:9125/udp"
    volumes:
      - "./statsd_mapping.yml:/tmp/statsd_mapping.yml"

  prometheus:
    image: prom/prometheus
    command: "--config.file=/tmp/prometheus.yml --web.listen-address '0.0.0.0:9090'"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/tmp/prometheus.yml"
